from script import load_image
from script import load_image, pygame

enemy_image=pygame.image.load('image/enemy/bag.png').convert_alpha()
enemy2_image=pygame.image.load('image/enemy/right.png').convert_alpha()
enemy3_image=pygame.image.load('image/enemy/crab.png').convert_alpha()
tower_1_image = load_image('image/tower 1/tower')
tower_1_of = pygame.image.load('image/tower 1/1_of.png').convert_alpha()
tower_1_on = pygame.image.load('image/tower 1/1_on.png').convert_alpha()
tower_1_bullet = pygame.image.load('image/tower 1/bullet 1.png').convert_alpha()
tower_1_1_image = load_image('image/tower 1_1/tower')
tower_2_image = load_image('image/tower 2/tower')
tower_2_of = pygame.image.load('image/tower 2/tower2_of.png').convert_alpha()
tower_2_on = pygame.image.load('image/tower 2/tower2_on.png').convert_alpha()
tower_2_bullet = pygame.image.load('image/tower 2/bullet.png').convert_alpha()
tower_2_1_image = load_image('image/tower 2_1/tower')
tower_3_image = load_image('image/tower 3/tower')
tower_3_of = pygame.image.load('image/tower 3/of.png').convert_alpha()
tower_3_on = pygame.image.load('image/tower 3/on.png').convert_alpha()
tower_3_bullet = pygame.image.load('image/tower 3/bullet.png').convert_alpha()
tower_3_1_image = load_image('image/tower 3_1/tower')
bottom_image = pygame.image.load('image/tile map/bottom.png').convert_alpha()
bush_image = pygame.image.load('image/tile map/bush_tile 1.png').convert_alpha()
tower_bush_image = pygame.image.load('image/tile map/bush_tile_tower.png').convert_alpha()
grass_image = pygame.image.load('image/tile map/grass_tile_1.png').convert_alpha()
left_image = pygame.image.load('image/tile map/left.png').convert_alpha()
right_image = pygame.image.load('image/tile map/right.png').convert_alpha()
top_image = pygame.image.load('image/tile map/top.png').convert_alpha()
panel_image=pygame.image.load('image/panel.jpg').convert_alpha()
upgrade_image = pygame.image.load('image/upgrade.png').convert_alpha()
button_image = pygame.image.load('image/button.png').convert_alpha()